on:
  push:
    branches: [main]
jobs:
  goaction:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Build and push
      run: |
         docker build -t example example/
    - name: Test
      uses: ./
      with:
        appDescription: "foo"
        appName: "wget"
        image: "example"
        appEntrypoint: "/usr/bin/wget"
        output: "./wget"
        appStore: "$HOME/.store"
        
    - name: "Check files were built"
      run: |
            ls -liah
            ./wget www.google.com
